//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WisaApi.WISA {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WISA.WisaAPIService")]
    internal interface WisaAPIService {
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:WisaAPIService-WisaAPIService#GetExportData", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(TWISAAPIParamValue))]
        WisaApi.WISA.GetExportDataResponse GetExportData(WisaApi.WISA.GetExportDataRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:WisaAPIService-WisaAPIService#GetExportData", ReplyAction="*")]
        System.Threading.Tasks.Task<WisaApi.WISA.GetExportDataResponse> GetExportDataAsync(WisaApi.WISA.GetExportDataRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:WisaAPIService-WisaAPIService#GetCSVData", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(TWISAAPIParamValue))]
        WisaApi.WISA.GetCSVDataResponse GetCSVData(WisaApi.WISA.GetCSVDataRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:WisaAPIService-WisaAPIService#GetCSVData", ReplyAction="*")]
        System.Threading.Tasks.Task<WisaApi.WISA.GetCSVDataResponse> GetCSVDataAsync(WisaApi.WISA.GetCSVDataRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:WisaAPIService-WisaAPIService#GetXMLData", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(TWISAAPIParamValue))]
        WisaApi.WISA.GetXMLDataResponse GetXMLData(WisaApi.WISA.GetXMLDataRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:WisaAPIService-WisaAPIService#GetXMLData", ReplyAction="*")]
        System.Threading.Tasks.Task<WisaApi.WISA.GetXMLDataResponse> GetXMLDataAsync(WisaApi.WISA.GetXMLDataRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:WisaAPIService")]
    public partial class TWISAAPICredentials : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string usernameField;
        
        private string passwordField;
        
        private string databaseField;
        
        /// <remarks/>
        public string Username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
                this.RaisePropertyChanged("Username");
            }
        }
        
        /// <remarks/>
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("Password");
            }
        }
        
        /// <remarks/>
        public string Database {
            get {
                return this.databaseField;
            }
            set {
                this.databaseField = value;
                this.RaisePropertyChanged("Database");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:WisaAPIService")]
    public partial class TWISAAPIParamValue : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nameField;
        
        private string valueField;
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetExportData", WrapperNamespace="urn:WisaAPIService-WisaAPIService", IsWrapped=true)]
    internal partial class GetExportDataRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public WisaApi.WISA.TWISAAPICredentials Credentials;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string QueryCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string Format;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public WisaApi.WISA.TWISAAPIParamValue[] Params;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=4)]
        public string Options;
        
        public GetExportDataRequest() {
        }
        
        public GetExportDataRequest(WisaApi.WISA.TWISAAPICredentials Credentials, string QueryCode, string Format, WisaApi.WISA.TWISAAPIParamValue[] Params, string Options) {
            this.Credentials = Credentials;
            this.QueryCode = QueryCode;
            this.Format = Format;
            this.Params = Params;
            this.Options = Options;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetExportDataResponse", WrapperNamespace="urn:WisaAPIService-WisaAPIService", IsWrapped=true)]
    internal partial class GetExportDataResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        [System.Xml.Serialization.SoapElementAttribute(DataType="base64Binary")]
        public byte[] Result;
        
        public GetExportDataResponse() {
        }
        
        public GetExportDataResponse(byte[] Result) {
            this.Result = Result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetCSVData", WrapperNamespace="urn:WisaAPIService-WisaAPIService", IsWrapped=true)]
    internal partial class GetCSVDataRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public WisaApi.WISA.TWISAAPICredentials Credentials;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string QueryCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public WisaApi.WISA.TWISAAPIParamValue[] Params;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public bool Header;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=4)]
        public string Separator;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=5)]
        public string Options;
        
        public GetCSVDataRequest() {
        }
        
        public GetCSVDataRequest(WisaApi.WISA.TWISAAPICredentials Credentials, string QueryCode, WisaApi.WISA.TWISAAPIParamValue[] Params, bool Header, string Separator, string Options) {
            this.Credentials = Credentials;
            this.QueryCode = QueryCode;
            this.Params = Params;
            this.Header = Header;
            this.Separator = Separator;
            this.Options = Options;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetCSVDataResponse", WrapperNamespace="urn:WisaAPIService-WisaAPIService", IsWrapped=true)]
    internal partial class GetCSVDataResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        [System.Xml.Serialization.SoapElementAttribute(DataType="base64Binary")]
        public byte[] Result;
        
        public GetCSVDataResponse() {
        }
        
        public GetCSVDataResponse(byte[] Result) {
            this.Result = Result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetXMLData", WrapperNamespace="urn:WisaAPIService-WisaAPIService", IsWrapped=true)]
    internal partial class GetXMLDataRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public WisaApi.WISA.TWISAAPICredentials Credentials;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string QueryCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public WisaApi.WISA.TWISAAPIParamValue[] Params;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public int XMLFormat;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=4)]
        public string Options;
        
        public GetXMLDataRequest() {
        }
        
        public GetXMLDataRequest(WisaApi.WISA.TWISAAPICredentials Credentials, string QueryCode, WisaApi.WISA.TWISAAPIParamValue[] Params, int XMLFormat, string Options) {
            this.Credentials = Credentials;
            this.QueryCode = QueryCode;
            this.Params = Params;
            this.XMLFormat = XMLFormat;
            this.Options = Options;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetXMLDataResponse", WrapperNamespace="urn:WisaAPIService-WisaAPIService", IsWrapped=true)]
    internal partial class GetXMLDataResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        [System.Xml.Serialization.SoapElementAttribute(DataType="base64Binary")]
        public byte[] Result;
        
        public GetXMLDataResponse() {
        }
        
        public GetXMLDataResponse(byte[] Result) {
            this.Result = Result;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    internal interface WisaAPIServiceChannel : WisaApi.WISA.WisaAPIService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    internal partial class WisaAPIServiceClient : System.ServiceModel.ClientBase<WisaApi.WISA.WisaAPIService>, WisaApi.WISA.WisaAPIService {
        
        public WisaAPIServiceClient() {
        }
        
        public WisaAPIServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WisaAPIServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WisaAPIServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WisaAPIServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WisaApi.WISA.GetExportDataResponse GetExportData(WisaApi.WISA.GetExportDataRequest request) {
            return base.Channel.GetExportData(request);
        }
        
        public System.Threading.Tasks.Task<WisaApi.WISA.GetExportDataResponse> GetExportDataAsync(WisaApi.WISA.GetExportDataRequest request) {
            return base.Channel.GetExportDataAsync(request);
        }
        
        public WisaApi.WISA.GetCSVDataResponse GetCSVData(WisaApi.WISA.GetCSVDataRequest request) {
            return base.Channel.GetCSVData(request);
        }
        
        public System.Threading.Tasks.Task<WisaApi.WISA.GetCSVDataResponse> GetCSVDataAsync(WisaApi.WISA.GetCSVDataRequest request) {
            return base.Channel.GetCSVDataAsync(request);
        }
        
        public WisaApi.WISA.GetXMLDataResponse GetXMLData(WisaApi.WISA.GetXMLDataRequest request) {
            return base.Channel.GetXMLData(request);
        }
        
        public System.Threading.Tasks.Task<WisaApi.WISA.GetXMLDataResponse> GetXMLDataAsync(WisaApi.WISA.GetXMLDataRequest request) {
            return base.Channel.GetXMLDataAsync(request);
        }
    }
}
